/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.ke.shardx.jasper.reports.example;

import java.awt.BorderLayout;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Comparator;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Shady
 */
public class ReportGen extends javax.swing.JFrame {

    /**
     * Creates new form ReportGen
     */
    public ReportGen() {
        initComponents();
        CreateFiles();
        populateClasses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        cboCohort = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButton1.setText("Show Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset Reports");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );

        jButton3.setText("Show Courses Embedded");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\LOBI-College-MIS\\src\\lobi\\college\\mis\\resources\\gfx\\research.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level", "Course ID", "Department ID", "CourseFormat" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton5.setText("Get");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cboCohort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCohort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCohortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboCohort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(jComboBox1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(cboCohort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection cnn = Connect.getConnection();
        String reportPath = "report.jrxml";
        try {
            JasperReport jr = JasperCompileManager.compileReport(reportPath);
            //JOptionPane.showMessageDialog(null, conn);
            HashMap param = new HashMap();
            JasperPrint jp = JasperFillManager.fillReport(jr, param, cnn);
            JasperViewer.viewReport(jp);
            cnn.close();

        } catch (Exception e1) {
            JOptionPane.showMessageDialog(null, e1.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {

            jPanel1.removeAll();
            jPanel1.revalidate();
            jPanel1.repaint();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    private void resetPanel() {
        try {

            jPanel1.removeAll();
            jPanel1.revalidate();
            jPanel1.repaint();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        resetPanel();
        Connection cnn = Connect.getConnection();
        String reportPath = "reports/Courses3.jrxml";
//      InputStream inputStream = this.getClass().getResourceAsStream(reportPath);
//       System.out.println(inputStream != null);
        try {
//             String url = this.getClass().getResource("reports/Courses3.jrxml").getPath();
//        System.out.println(">>>"+url);
//      }catch (Exception ex){
//          System.out.println(ex.getMessage());
//      }
//     try { 
            //JasperDesign jasperDesign = JRXmlLoader.load(inputStream);
            JasperReport jr = JasperCompileManager.compileReport(getClass().getResourceAsStream(reportPath));

            //JasperReport jr = JasperCompileManager.compileReport(jasperDesign);
            //JOptionPane.showMessageDialog(null, conn);
            HashMap param = new HashMap();
            JasperPrint jp = JasperFillManager.fillReport(jr, param, cnn);
            //JasperViewer.viewReport(jp);
            JRViewer vw = new JRViewer(jp);
            jPanel1.setLayout(new BorderLayout());
            jPanel1.repaint();
            jPanel1.add(vw);
            jPanel1.revalidate();
            cnn.close();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            System.out.println(ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {

            Connection cnn = Connect.getConnection();
            resetPanel();

            //  String reportPath = "reports/Courses3.jas";
            // File theFile = new File(reportPath);
            // String reportPath = "./reports/Courses3.jrxml";
            String reportPath = "rps/Courses3.jrxml";
            System.out.println(reportPath);
            // InputStream input = this.getClass().getResourceAsStream(reportPath);
            //
            JasperDesign jasperDesign = JRXmlLoader.load(reportPath);

            String strQuery;
            switch (jComboBox1.getSelectedItem().toString()) {
                case "Level":
                    strQuery = "select * from courses Where Level Like '%" + jTextField1.getText() + "%'";
                    break;
                case "Course ID":
                    strQuery = "select * from courses Where CourseID =" + jTextField1.getText() + "";
                    break;
                case "Department ID":
                    strQuery = "select * from courses Where DeptID = " + jTextField1.getText() + "";
                    break;
                case "CourseFormat":
                    strQuery = "select * from courses Where CourseFormat Like '%" + jTextField1.getText() + "%'";
                    break;
                default:
                    strQuery = "select * from courses";
                    break;
            }
            //Build a new query
            System.out.println(strQuery);
            // update the data query
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(strQuery);
            jasperDesign.setQuery(newQuery);

            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);

            JasperPrint jp = JasperFillManager.fillReport(jasperReport, null, cnn);
            JRViewer vw = new JRViewer(jp);
            jPanel1.setLayout(new BorderLayout());
            jPanel1.repaint();
            jPanel1.add(vw);
            jPanel1.revalidate();
            cnn.close();
        } catch (Exception ex) {
            String connectMsg = "Could not create the report " + ex.getMessage() + " " + ex.getLocalizedMessage();
            System.out.println(connectMsg);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    // TODO add your handling code here:
        try {

            Connection cnn = Connect.getConnection();
            resetPanel();

            //  String reportPath = "reports/Courses3.jas";
            // File theFile = new File(reportPath);
            // String reportPath = "./reports/Courses3.jrxml";
            String reportPath = "rps/classlist.jrxml";
            System.out.println(reportPath);
            // InputStream input = this.getClass().getResourceAsStream(reportPath);
            //
            JasperDesign jasperDesign = JRXmlLoader.load(reportPath);

            String strQuery;
            
                    strQuery = "SELECT CSR.STUDENTID, STUD.STUDENT_NAME FROM STUDENTS STUD INNER JOIN COURSEENROLLMENT CSR ON STUD.STUDENTID=CSR.STUDENTID WHERE  CSR.Cohort='"+cboCohort.getSelectedItem() +"'";
                  
            //Build a new query
            System.out.println(strQuery);
            // update the data query
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(strQuery);
            jasperDesign.setQuery(newQuery);

            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);

            JasperPrint jp = JasperFillManager.fillReport(jasperReport, null, cnn);
            JRViewer vw = new JRViewer(jp);
            jPanel1.setLayout(new BorderLayout());
            jPanel1.repaint();
            jPanel1.add(vw);
            jPanel1.revalidate();
            cnn.close();
        } catch (Exception ex) {
            String connectMsg = "Could not create the report " + ex.getMessage() + " " + ex.getLocalizedMessage();
            System.out.println(connectMsg);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        File file = new File("rps");
        deleteFile(file);
    }//GEN-LAST:event_formWindowClosing

    private void cboCohortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCohortActionPerformed
        // TODO add your handling code here:
        System.out.println(cboCohort.getSelectedItem());
    }//GEN-LAST:event_cboCohortActionPerformed
    public static void deleteFile(File element) {
        if (element.isDirectory()) {
            for (File sub : element.listFiles()) {
                deleteFile(sub);
            }
        }
        element.delete();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportGen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportGen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboCohort;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void CreateFiles() {
        new File("rps").mkdir();
        try {
            Connect.reportFiles(getClass().getResourceAsStream("reports/Courses3.jrxml"), "rps/Courses3.jrxml");
            Connect.reportFiles(getClass().getResourceAsStream("reports/classList.jrxml"), "rps/classlist.jrxml");

        } catch (IOException ex) {
            Logger.getLogger(ReportGen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void populateClasses() {
        String Query="SELECT * FROM cohorts WHERE cohorts.DeptID ='1'";
        System.out.println(Query);
          try {
            Connection cnn = Connect.getConnection();
            Statement st = cnn.createStatement();
            cboCohort.removeAllItems();
            ResultSet rs = st.executeQuery(Query);

            while (rs.next()) {
                cboCohort.addItem(rs.getString("cohortName"));
            }

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(this, "When Populating Cohorts," + e.getMessage(), "Error Occured", JOptionPane.ERROR_MESSAGE);

        }
    }

}
